server.port=8080

# Plugin configuration
plugins.directory=../plugins

# Default profile: h2
spring.profiles.active=h2

# Common JPA settings
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Seed data
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# OpenAPI
springdoc.api-docs.path=/v3/api-docs
